# Generated by Django 5.0.7 on 2024-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perslib',
            name='image_url',
        ),
        migrations.AddField(
            model_name='perslib',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
